workspace: true

stages:
  - build
  - test

jobs:
  - name: build:prepare
    stage: build
    image: sunci/ruby:3.0.2
    script:
      - cp database-ci.yml config/database.yml
      - bundle _2.1.4_ install --path vendor/bundle # _2.1.4_ if ruby 2.7.1 or 3.0.2
    cache:
      - key: vendor_$CI_BRANCH
        paths:
          - vendor/bundle

  # - name: test:rspec
  #   stage: test
  #   image: sunci/ruby:3.0.2
  #   services:
  #     - image: mysql:5.7.22
  #       name: mysql_test
  #       environment:
  #         MYSQL_DATABASE: db_test
  #         MYSQL_USER: user_test
  #         MYSQL_PASSWORD: password_test
  #         MYSQL_ROOT_PASSWORD: password_test
  #   before_script:
  #     - bundle _2.1.4_ install --path vendor/bundle # _2.1.4_ if ruby 2.7.1 or 3.0.2
  #   script:
  #     - RAILS_ENV=test bundle exec rails db:drop db:create db:migrate
  #     - bundle _2.1.4_ exec rspec # _2.1.4_ if ruby 2.7.1 or 3.0.2

  - name: test:rubocop
    stage: test
    image: sunci/ruby:3.0.2
    before_script:
      - bundle _2.1.4_ install --path vendor/bundle # _2.1.4_ if ruby 2.7.1 or 3.0.2
    script:
      - bundle exec rubocop --require rubocop/formatter/checkstyle_formatter --format RuboCop::Formatter::CheckstyleFormatter --no-color app/ lib/
